# Generated by Django 5.2.7 on 2025-10-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('total_duration', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('spotify_id', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
            ],
        ),
    ]
