"""
Django settings for aiplaylist project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import warnings
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
def _bool_env(var_name: str, default: bool = False) -> bool:
    raw = os.getenv(var_name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


DEBUG = _bool_env("DJANGO_DEBUG", default=True)

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "dev-insecure-placeholder-key"
        warnings.warn(
            "DJANGO_SECRET_KEY was not set; using insecure development key.",
            RuntimeWarning,
        )
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY environment variable must be set.")

_raw_allowed_hosts = os.getenv(
    "DJANGO_ALLOWED_HOSTS",
    "0.0.0.0,localhost,127.0.0.1,192.168.1.111,aiplaylistgenerator.app,aiplaylistgenerator-not-docker.onrender.com",
)
ALLOWED_HOSTS = [host.strip() for host in _raw_allowed_hosts.split(",") if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'dashboard',
    'explorer',
    'spotify_auth',
    'recommender',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aiplaylist.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aiplaylist.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Spotify API Access
SPOTIFY_LOGIN_URL = 'https://accounts.spotify.com/en/login'
SPOTIFY_AUTH_URL = 'https://accounts.spotify.com/api/token'
SPOTIFY_CLIENT_ID = os.getenv('SPOTIFY_CLIENT_ID')
SPOTIFY_CLIENT_SECRET = os.getenv('SPOTIFY_CLIENT_SECRET')
SPOTIFY_REDIRECT_URI = os.getenv('SPOTIFY_REDIRECT_URI', 'http://localhost:8000/spotify/callback/')

_DEFAULT_SPOTIFY_SCOPES = [
    'user-read-email',
    'user-read-private',
    'user-read-recently-played',
    'user-top-read',
    'user-library-read',
    'playlist-read-private',
    'playlist-modify-private',
    'playlist-modify-public',
]

_raw_spotify_scopes = os.getenv("SPOTIFY_SCOPES")
if _raw_spotify_scopes:
    SPOTIFY_SCOPES = [
        scope.strip()
        for scope in _raw_spotify_scopes.replace(",", " ").split()
        if scope.strip()
    ]
else:
    SPOTIFY_SCOPES = _DEFAULT_SPOTIFY_SCOPES[:]


SPOTIFY_USE_RECOMMENDATIONS = True


def _int_env(var_name: str, default: int) -> int:
    raw = os.getenv(var_name)
    if raw is None:
        return default
    try:
        return int(raw.strip())
    except (TypeError, ValueError):
        return default


def _float_env(var_name: str, default: float) -> float:
    raw = os.getenv(var_name)
    if raw is None:
        return default
    try:
        return float(raw.strip())
    except (TypeError, ValueError):
        return default


RECOMMENDER_PLAYLIST_PREFIX = os.getenv("RECOMMENDER_PLAYLIST_PREFIX", "TEST ")
RECOMMENDER_PLAYLIST_PUBLIC = _bool_env("RECOMMENDER_PLAYLIST_PUBLIC", default=False)
RECOMMENDER_DEBUG_VIEW_ENABLED = _bool_env("RECOMMENDER_DEBUG_VIEW_ENABLED", default=DEBUG)
RECOMMENDER_CACHE_TIMEOUT_SECONDS = _int_env("RECOMMENDER_CACHE_TIMEOUT_SECONDS", 60 * 15)
RECOMMENDER_OPENAI_MODEL = os.getenv("RECOMMENDER_OPENAI_MODEL", "gpt-4o-mini")
RECOMMENDER_OPENAI_TEMPERATURE = _float_env("RECOMMENDER_OPENAI_TEMPERATURE", 0.7)
RECOMMENDER_OPENAI_MAX_TOKENS = _int_env("RECOMMENDER_OPENAI_MAX_TOKENS", 512)
RECOMMENDER_LLM_DEFAULT_PROVIDER = os.getenv("RECOMMENDER_LLM_DEFAULT_PROVIDER", "openai").lower()
RECOMMENDER_OLLAMA_MODEL = os.getenv("RECOMMENDER_OLLAMA_MODEL", "mistral")
_default_ollama_timeout = 600 if DEBUG else 60
RECOMMENDER_OLLAMA_TIMEOUT_SECONDS = _int_env(
    "RECOMMENDER_OLLAMA_TIMEOUT_SECONDS",
    _default_ollama_timeout,
)

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_API_BASE = os.getenv("OPENAI_API_BASE")
OPENAI_ORGANIZATION = os.getenv("OPENAI_ORGANIZATION") or os.getenv("OPENAI_ORG_ID")

# Placeholder knobs for upcoming user-configurable recommender options.
RECOMMENDER_DEFAULT_PLAYLIST_LENGTH = _int_env("RECOMMENDER_DEFAULT_PLAYLIST_LENGTH", 20)
RECOMMENDER_MIN_PLAYLIST_LENGTH = _int_env("RECOMMENDER_MIN_PLAYLIST_LENGTH", 5)
RECOMMENDER_MAX_PLAYLIST_LENGTH = _int_env("RECOMMENDER_MAX_PLAYLIST_LENGTH", 60)
RECOMMENDER_EXPERIMENTAL_FLAGS = {
    "enforce_unique_tracks": _bool_env("RECOMMENDER_ENFORCE_UNIQUE_DEFAULT", True),
    "allow_seed_only_playlists": _bool_env("RECOMMENDER_ALLOW_SEED_ONLY_DEFAULT", False),
}

if not DEBUG:
    SECURE_SSL_REDIRECT = _bool_env("DJANGO_SECURE_SSL_REDIRECT", True)
    SESSION_COOKIE_SECURE = _bool_env("DJANGO_SESSION_COOKIE_SECURE", True)
    CSRF_COOKIE_SECURE = _bool_env("DJANGO_CSRF_COOKIE_SECURE", True)
    SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _bool_env("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", True)
    SECURE_HSTS_PRELOAD = _bool_env("DJANGO_SECURE_HSTS_PRELOAD", True)
