# Generated by Django 5.2.7 on 2025-10-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=64, unique=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('creator_user_id', models.CharField(max_length=64)),
            ],
        ),
    ]
