# Generated by Django 5.2.7 on 2025-11-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedplaylist',
            name='creator_display_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
