# Generated by Django 5.2.7 on 2025-11-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_playlistgenerationstat'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='playlistgenerationstat',
            new_name='recommender_user_id_bd4071_idx',
            old_name='recommende_user_id_9fb003_idx',
        ),
    ]
