# Generated by Django 5.2.7 on 2025-11-07 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_savedplaylist_creator_display_name'),
        ('recommender', '0004_playlistgenerationstat_tokens'),
    ]

    operations = [
    ]
