# Generated by Django 5.2.8 on 2025-11-13 02:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_merge_20251107_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedplaylist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='savedplaylist',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='savedplaylist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedplaylist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='savedplaylist',
            name='playlist_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedplaylist',
            name='spotify_uri',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='savedplaylist',
            name='total_duration_ms',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savedplaylist',
            name='track_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
