# Generated by Django 5.2.8 on 2025-11-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_alter_savedplaylist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedplaylist',
            name='like_count',
        ),
        migrations.CreateModel(
            name='UniqueLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('playlist_id', models.CharField(max_length=64)),
            ],
            options={
                'unique_together': {('user_id', 'playlist_id')},
            },
        ),
    ]
