# Generated by Django 5.2.8 on 2025-12-04 17:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_remove_savedplaylist_like_count_uniquelike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedplaylist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
