# Generated by Django 5.2.8 on 2025-11-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follower_user_id", models.CharField(db_index=True, max_length=64)),
                ("follower_display_name", models.CharField(max_length=255)),
                ("following_user_id", models.CharField(db_index=True, max_length=64)),
                ("following_display_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["follower_user_id", "-created_at"],
                        name="dashboard_u_followe_65a802_idx",
                    ),
                    models.Index(
                        fields=["following_user_id", "-created_at"],
                        name="dashboard_u_followi_1995c1_idx",
                    ),
                ],
                "unique_together": {("follower_user_id", "following_user_id")},
            },
        ),
    ]
